### ISSUE TITLE
Toggle Map/Concerts

### ISSUE THREAD

**Issue by jthielman** [nss-evening-cohort-10/foundations-group-project-bleach-boys#14]
# User Story
As a user, I'd like to see a list of concert dates, and then when an entry is clicked, I'd like a map of the location to show underneath that list item

# AC
**When** the page loads, only the list of locations and times shows up
**Then** I click an entry, and an image shows up (screenshot of google map), preferably with nice animation.
**And** any other map that's showing should close at the same time

# Dev Notes
Use this: https://getbootstrap.com/docs/4.3/components/collapse/#accordion-example
Make the whole div clickable, not just the text inside

**Comment by jthielman** [comment]
![image](https://user-images.githubusercontent.com/54124593/64912464-76349580-d6f5-11e9-897f-8b006c92690b.png)

**Comment by zoeames** [comment]
screenshot of google map here is cool.  don't try to integrate full google maps
