### ISSUE TITLE
Create Images folder

### ISSUE THREAD

**Issue by ivannio** [nss-evening-cohort-10/foundations-group-project-bleach-boys#15]
# User Story:
As a developer, I want to have a directory in which all of my images will be contained and linked from

# AC:
**WHEN** I run `ls` in the project directory
**THEN** I should see an images directory in which all site images will be contained

# Dev notes:
* Upon finding relevant images for your designated page, download and move to the /images directory
* link all images from images as follows:
```html
<img src="/images/YOURIMAGE.jpg>
```

**Comment by Ojaswy** [comment]
Where exactly are you looking to create a folder?

In Linux you can create a folder by using the command: mkdir images
