### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by ivannio** [nss-evening-cohort-10/foundations-group-project-bleach-boys#4]
# User story
As a user, I'd like to see a footer at the bottom of the page with some links to social media, so I can find this band's presence on other sites

# AC
**When** the page loads
**Then** there should be a footer at the bottom with social media links: facebook, twitter, youtube, instagram, soundcloud.  Also a copyright thing.
**And** the links should lead somewhere.  And be centered.  With the copyright thing underneath the links.  And the links should be icons.

# Dev Notes
Use fontawesome for the icons, and a bootstrap nav (see below for a centered version) for the structure of the footer.  Nest that nav in footer tags for readability.

```html
<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>
```

**Comment by ivannio** [comment]
![image](https://user-images.githubusercontent.com/21040719/64911349-429e3f00-d6e6-11e9-83a1-06ba72ee70e1.png)

**Comment by jthielman** [comment]
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<i class="fab fa-facebook-square"></i>
<i class="fab fa-twitter-square"></i>
<i class="fab fa-youtube-square"></i>
<i class="fab fa-instagram"></i>
<i class="fab fa-soundcloud"></i>
```
