### ISSUE TITLE
Popular Gear/Home

### ISSUE THREAD

**Issue by ivannio** [nss-evening-cohort-10/foundations-group-project-bleach-boys#7]
**USER STORY**
As a user I want to see the most popular Gear other fans are purchasing, and be able to click a button on those items that will take me to the store page.

**AC**
*Displays the three most popular items.
*buttons on card link to Store

**DEV**
Use looping array grabbing only those "Gear Objects" with a key of "p" for popular

MAYBE: Button links to store page and auto filters store page based on product type?

**Comment by ivannio** [comment]
![image](https://user-images.githubusercontent.com/21040719/64911393-de2faf80-d6e6-11e9-8cb9-e0a8859924cb.png)

**Comment by evangdesigns** [comment]
<img width="495" alt="Screen Shot 2019-09-14 at 12 50 20 PM" src="https://user-images.githubusercontent.com/26425684/64911981-45049700-d6ee-11e9-8cba-f1859f767458.png">
