### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by jbkey2015** [nss-evening-cohort-10/foundations-group-project-bleach-boys#8]
**User Story**
As a developer, when I do stuff I would like to see some wireframes

**AC**
**WHEN** I open this ticket
**THEN** I should see screenshots for each page

**Dev Notes**
*Use Moquops to generate wireframes
*paste them into this ticket

**Comment by ivannio** [comment]
Home: 
![image](https://user-images.githubusercontent.com/21040719/64911440-5a29f780-d6e7-11e9-9704-435ace68792e.png)

**Comment by jbkey2015** [comment]
![image](https://user-images.githubusercontent.com/54037058/64911507-32875f00-d6e8-11e9-845c-e8e4d5a7b005.png)

**Comment by ivannio** [comment]
Music Page: 
![image](https://user-images.githubusercontent.com/21040719/64911716-ef7abb00-d6ea-11e9-8ffc-0aa095bf1a1a.png)

**Comment by archeni** [comment]
![image](https://user-images.githubusercontent.com/54213010/64912326-2bb21980-d6f3-11e9-8d07-7859bb3a8625.png)

**Comment by jthielman** [comment]
![image](https://user-images.githubusercontent.com/54124593/64912352-83508500-d6f3-11e9-91fd-382cd107098e.png)

**Comment by archeni** [comment]
![image](https://user-images.githubusercontent.com/54213010/64912490-c7dd2000-d6f5-11e9-8c6a-f571120b7b88.png)

**Comment by evangdesigns** [comment]
NAV BAR
![Navbar](https://user-images.githubusercontent.com/26425684/65003534-89469180-d8be-11e9-942c-a3b0a33167c5.jpg)

**Comment by evangdesigns** [comment]
Product/Album card styling

![cardStyle](https://user-images.githubusercontent.com/26425684/65003545-92cff980-d8be-11e9-957e-6c19152a3808.jpg)
