### ISSUE TITLE
Available albums page

### ISSUE THREAD

**Issue by ivannio** [nss-evening-cohort-10/foundations-group-project-bleach-boys#9]
# User Story:
As a user, I want to be able to see the artist's available albums and have a link to bandcamp for each album in the title

# AC:
**WHEN** the page loads
**THEN** I should see cards that contain an image of the album cover, the album title, and all of the song titles on each album
**AND** each album title should be a hyperlink that sends the user to bandcamp

# Dev Notes:
* use bootstrap horizontal cards for each album
* create array of objects each representing an album
* create a function named `albumCardPrinter` that runs on page load that builds a html string to print to DOM using `printToDOM` function
* `albumCardPrinter` function should loop through the array of albums and populate bootstrap horizontal card htmlstring with key value pair data then `printToDOM`
* data should be formatted as follows:
```javascript
const albums = [
{ 
coverUrl: 'cover.jpg',
title: 'Album Title',
songs: ['Song 1', 'Song 2', 'Song 3', 'Song 4', 'Song 5', 'Song 6', 'Song 7'],
albumUrl: 'bandcamp.com'
},
{ 
coverUrl: 'cover.jpg',
title: 'Album Title',
songs: ['Song 1', 'Song 2', 'Song 3', 'Song 4', 'Song 5', 'Song 6', 'Song 7'],
albumUrl: 'bandcamp.com'
},
{ 
coverUrl: 'cover.jpg',
title: 'Album Title',
songs: ['Song 1', 'Song 2', 'Song 3', 'Song 4', 'Song 5', 'Song 6', 'Song 7'],
albumUrl: 'bandcamp.com'
},
{ 
coverUrl: 'cover.jpg',
title: 'Album Title',
songs: ['Song 1', 'Song 2', 'Song 3', 'Song 4', 'Song 5', 'Song 6', 'Song 7'],
albumUrl: 'bandcamp.com'
}
];
```

**Comment by ivannio** [comment]
![image](https://user-images.githubusercontent.com/21040719/64911724-08836c00-d6eb-11e9-9183-d7e78171d11e.png)

**Comment by ivannio** [comment]
***Bootstrap horizontal card***

```html
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="..." class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
```

**Comment by evangdesigns** [comment]
Styling
![cardStyle](https://user-images.githubusercontent.com/26425684/65003061-56030300-d8bc-11e9-9a5e-8f2e15da6bfd.jpg)
